
app: vjepa_droid
cpus_per_task: 4            # OPTIMIZED: Colab typically offers 2-4 vCPUs. 12 will error.
folder: mydroiddata/droid-256px-8f
mem_per_gpu: 22G            # OPTIMIZED: Matches your L4 capacity.
nodes: 1                    # OPTIMIZED: You are running on a single Colab instance.
tasks_per_node: 1           # OPTIMIZED: Single process for single GPU.
data:
  batch_size: 4            # OPTIMIZED: L4 22GB can handle BS=4 with checkpointing. Increases stability.
  camera_views:
  - left_mp4_path
  crop_size: 224            # OPTIMIZED: Reduced from 256. 224 is standard/faster and saves VRAM.
  datasets:
    # CSV file, each line is a trajectory dir path
    # See https://github.com/facebookresearch/vjepa2/issues/65
    - mydroiddata/dataset/droid_raw/droid_index.csv
  dataset_fpcs:
  - 8
  fps: 6
  num_workers: 0           # OPTIMIZED: Matches low CPU core count on Colab to prevent bottlenecks.
  patch_size: 16
  pin_mem: true
  stereo_view: false
  tubelet_size: 2
data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.85                    # OPTIMIZED: Narrower range for more stable training on small batches.
  - 1.15
  random_resize_scale:
  - 0.8                     # OPTIMIZED: Less aggressive scaling to prevent information loss.
  - 1.0
  reprob: 0.0
loss:
  auto_steps: 2
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
meta:
  dtype: bfloat16           # OPTIMIZED: L4 Native support. Faster & less memory than float32.
  eval_freq: 50             # OPTIMIZED: More frequent evaluation since epochs are shorter.
  resume_checkpoint: null
  load_predictor: false
  pretrain_checkpoint: mydroiddata/droid-256px-8f/checkpoints/vitl.pt
  context_encoder_key: target_encoder
  target_encoder_key: target_encoder
  save_every_freq: 10
  seed: 239
  use_sdpa: true            # OPTIMIZED: Enables FlashAttention-2 on L4 GPU. Huge speedup.
model:
  model_name: vit_large
  pred_depth: 12
  pred_embed_dim: 1024
  pred_is_frame_causal: true
  pred_num_heads: 16
  uniform_power: true
  use_activation_checkpointing: true # CRITICAL: Allows ViT-Large to fit in 22GB VRAM.
  use_extrinsics: false
  use_rope: true
optimization:
  anneal: 0
  epochs: 100                # OPTIMIZED: Reduced from 315. Sufficient for a take-home demo.
  final_lr: 0.0001
  final_weight_decay: 0.04
  ipe: 300
  lr: 0.0001                # OPTIMIZED: Scaled down from 4e-4 for smaller batch size (4 vs ~2048).
  start_lr: 0.00001
  warmup: 5
  weight_decay: 0.04







# app: vjepa_droid
# cpus_per_task: 12
# folder: mydroiddata/droid-256px-8f
# mem_per_gpu: 220G
# nodes: 4
# tasks_per_node: 8
# data:
#   batch_size: 1
#   camera_views:
#   - left_mp4_path
#   crop_size: 256
#   datasets:
#     # CSV file, each line is a trajectory dir path
#     # See https://github.com/facebookresearch/vjepa2/issues/65
#     - mydroiddata/droid-256px-8f/dataset/droid_100/1.0.0/droid_index.csv
#   dataset_fpcs:
#   - 8
#   fps: 1
#   num_workers: 2
#   patch_size: 16
#   pin_mem: true
#   stereo_view: false
#   tubelet_size: 2
# data_aug:
#   auto_augment: false
#   horizontal_flip: false
#   motion_shift: false
#   random_resize_aspect_ratio:
#   - 0.75
#   - 1.35
#   random_resize_scale:
#   - 1.777
#   - 1.777
#   reprob: 0.0
# loss:
#   auto_steps: 2
#   loss_exp: 1.0
#   normalize_reps: true
#   reg_coeff: 0.0
# meta:
#   dtype: bfloat16
#   eval_freq: 100
#   resume_checkpoint: null
#   load_predictor: false
#   pretrain_checkpoint: mydroiddata/droid-256px-8f/checkpoints/vitl.pt
#   context_encoder_key: target_encoder
#   target_encoder_key: target_encoder
#   save_every_freq: 25
#   seed: 239
#   use_sdpa: true
# model:
#   model_name: vit_large
#   pred_depth: 12
#   pred_embed_dim: 1024
#   pred_is_frame_causal: true
#   pred_num_heads: 16
#   uniform_power: true
#   use_activation_checkpointing: true
#   use_extrinsics: false
#   use_rope: true
# optimization:
#   anneal: 15
#   epochs: 315
#   final_lr: 0.0
#   final_weight_decay: 0.04
#   ipe: 300
#   lr: 0.000425
#   start_lr: 0.000075
#   warmup: 15
#   weight_decay: 0.04
